### ISSUE TITLE
RFC: Support for recommended config

### ISSUE THREAD

**Issue by amilajack** [jkimbo/eslint-plugin-jest#4]
Willing to make a PR for this. Would it be welcome?

**Comment by jkimbo** [comment]
Thanks for the offer @amilajack but this plugin has actually recently been merged into the main jest repo (https://github.com/facebook/jest/tree/master/packages/eslint-plugin-jest) and it also contains a recommended config. I'm hoping it will be released shortly when the next version of jest comes out.

**Comment by jkimbo** [comment]
As of jest v19.0.0 this plugin is published from the main jest repo: https://github.com/facebook/jest/tree/master/packages/eslint-plugin-jest
